# Generated by Django 3.2.7 on 2021-10-20 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantify',
            new_name='quantity',
        ),
    ]
