# Generated by Django 3.2.7 on 2021-11-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_ordership'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ordership',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
