# Generated by Django 3.2.7 on 2021-11-11 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_shippingaddress_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='shipping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.shippingaddress'),
        ),
    ]
